apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filestash
  labels:
    app.kubernetes.io/name: filestash
    app.kubernetes.io/component: filestash
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: filestash.k8s-test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filestash
                port:
                  number: 8334
