apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: path-graph
resources:
  - namespace.yaml
  - workflow-templates/pipeline-ingest-rag.yaml
  - workflow-templates/pipeline-graph.yaml
  - workflow-templates/pipeline-wiki.yaml
  - workflow-templates/pipeline-graphrag.yaml
