apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: path-graph
resources:
  - ../../base
images:
  - name: path-graph/pipeline
    newName: ghcr.io/yoosungung/path-graph/pipeline
    newTag: latest
