apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: path-graph
configurations:
  - kustomizeconfig.yaml
resources:
  - ../../base
images:
  - name: path-graph/pipeline
    newName: ghcr.io/yoosungung/path-graph/pipeline
    newTag: 27087bf271ed6e0f2ef5afb606ae96a0ec68749a
patches:
  - patch: |-
      - op: remove
        path: /spec/parallelism
    target:
      kind: WorkflowTemplate
      name: pipeline-ingest-rag
  - patch: |-
      - op: remove
        path: /spec/parallelism
    target:
      kind: WorkflowTemplate
      name: pipeline-collect-ingest-rag
  - patch: |-
      - op: replace
        path: /data/default-v1
        value: |
          s3:
            bucket: runtime-bundles
            endpoint: garage-s3.runtime.svc.cluster.local:3900
            insecure: true
            accessKeySecret:
              name: s3-creds
              key: S3_ACCESS_KEY_ID
            secretKeySecret:
              name: s3-creds
              key: S3_SECRET_ACCESS_KEY
    target:
      kind: ConfigMap
      name: path-graph-artifact-repositories
